### ISSUE TITLE
Update to Typescript 3.5

### ISSUE THREAD

**Issue by gavinr** [Esri/generator-esri-appbuilder-js#144]
https://devblogs.microsoft.com/typescript/announcing-typescript-3-5/

**Comment by sevenninety** [comment]
When I compile using v3.5.1 I get the following error:

`node_modules/typescript/lib/lib.es2015.promise.d.ts(129,21): error TS2304: Cannot find name 'Iterable'.`

Changing my *lib* settings in tsconfig.json to the following fixes the issue (i.e. add es2015.iterable):

`"lib": ["dom", "es5", "scripthost", "es2015.promise", "es2015.iterable"]`

My widgets appear to function correctly when tested in Chrome and IE.

I hope that helps.

**Comment by gavinr** [comment]
That change is now in place - thanks @sevenninety 🎉!
